import { supabase } from '@/integrations/supabase/client';

interface Holiday {
  name: string;
  date: string; // YYYY-MM-DD
}

function easter(year: number): Date {
  const a = year % 19;
  const b = Math.floor(year / 100);
  const c = year % 100;
  const d = Math.floor(b / 4);
  const e = b % 4;
  const f = Math.floor((b + 8) / 25);
  const g = Math.floor((b - f + 1) / 3);
  const h = (19 * a + b - d - g + 15) % 30;
  const i = Math.floor(c / 4);
  const k = c % 4;
  const l = (32 + 2 * e + 2 * i - h - k) % 7;
  const m = Math.floor((a + 11 * h + 22 * l) / 451);
  const month = Math.floor((h + l - 7 * m + 114) / 31);
  const day = ((h + l - 7 * m + 114) % 31) + 1;
  return new Date(year, month - 1, day);
}

function nthDayOfMonth(year: number, month: number, dayOfWeek: number, n: number): Date {
  const first = new Date(year, month, 1);
  const firstDay = first.getDay();
  let day = 1 + ((dayOfWeek - firstDay + 7) % 7) + (n - 1) * 7;
  return new Date(year, month, day);
}

function lastDayOfMonth(year: number, month: number, dayOfWeek: number): Date {
  const last = new Date(year, month + 1, 0);
  const diff = (last.getDay() - dayOfWeek + 7) % 7;
  return new Date(year, month, last.getDate() - diff);
}

function fmt(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

function calculateUpcomingHolidays(start: Date, end: Date): Holiday[] {
  const holidays: Holiday[] = [];
  const years = new Set<number>();
  for (let y = start.getFullYear(); y <= end.getFullYear(); y++) years.add(y);

  for (const y of years) {
    const fixed: [string, number, number][] = [
      ["New Year's Day", 0, 1],
      ["Valentine's Day", 1, 14],
      ['Independence Day', 6, 4],
      ['Halloween', 9, 31],
      ['Christmas Eve', 11, 24],
      ['Christmas Day', 11, 25],
      ["New Year's Eve", 11, 31],
    ];
    for (const [name, m, d] of fixed) {
      holidays.push({ name, date: fmt(new Date(y, m, d)) });
    }

    // Easter
    holidays.push({ name: 'Easter', date: fmt(easter(y)) });

    // Mother's Day — 2nd Sunday of May
    holidays.push({ name: "Mother's Day", date: fmt(nthDayOfMonth(y, 4, 0, 2)) });

    // Memorial Day — last Monday of May
    holidays.push({ name: 'Memorial Day', date: fmt(lastDayOfMonth(y, 4, 1)) });

    // Father's Day — 3rd Sunday of June
    holidays.push({ name: "Father's Day", date: fmt(nthDayOfMonth(y, 5, 0, 3)) });

    // Labor Day — 1st Monday of September
    holidays.push({ name: 'Labor Day', date: fmt(nthDayOfMonth(y, 8, 1, 1)) });

    // Thanksgiving — 4th Thursday of November
    const thanksgiving = nthDayOfMonth(y, 10, 4, 4);
    holidays.push({ name: 'Thanksgiving', date: fmt(thanksgiving) });

    // Black Friday — day after Thanksgiving
    const bf = new Date(thanksgiving);
    bf.setDate(bf.getDate() + 1);
    holidays.push({ name: 'Black Friday', date: fmt(bf) });

    // Cyber Monday — Monday after Thanksgiving
    const cm = new Date(thanksgiving);
    cm.setDate(cm.getDate() + 4);
    holidays.push({ name: 'Cyber Monday', date: fmt(cm) });
  }

  const startStr = fmt(start);
  const endStr = fmt(end);
  return holidays.filter(h => h.date >= startStr && h.date <= endStr);
}

export async function seedCalendarHolidays(brandId: string): Promise<number> {
  const today = new Date();
  const endDate = new Date(today);
  endDate.setDate(endDate.getDate() + 90);

  const holidays = calculateUpcomingHolidays(today, endDate);

  let seeded = 0;
  for (const holiday of holidays) {
    const { error } = await supabase
      .from('brand_calendar')
      .upsert(
        {
          brand_id: brandId,
          event_name: holiday.name,
          event_date: holiday.date,
          event_type: 'holiday',
          auto_generated: true,
        },
        { onConflict: 'brand_id,event_name,event_date' },
      );
    if (!error) seeded++;
  }

  return seeded;
}

export async function hasAutoGeneratedEvents(brandId: string): Promise<boolean> {
  const { count } = await supabase
    .from('brand_calendar')
    .select('id', { count: 'exact', head: true })
    .eq('brand_id', brandId)
    .eq('auto_generated', true);
  return (count || 0) > 0;
}
