import { useParams, useNavigate } from 'react-router-dom';
import { DndContext, DragEndEvent, DragOverlay, useSensor, useSensors, PointerSensor } from '@dnd-kit/core';
import { useIdeation } from '@/hooks/useIdeation';
import { useDesignQueue } from '@/hooks/useDesignQueue';
import { useIdeationCalendar } from '@/hooks/useIdeationCalendar';
import { CampaignTypePicker } from '@/components/ideation/CampaignTypePicker';
import { NodeFlow } from '@/components/ideation/NodeFlow';
import { ChatBar } from '@/components/ideation/ChatBar';
import { TaskWindow } from '@/components/ideation/TaskWindow';
import { ResizablePanelGroup, ResizablePanel, ResizableHandle } from '@/components/ui/resizable';
import { CampaignIdea } from '@/lib/types';
import { DesignQueueItem } from '@/hooks/useDesignQueue';
import { useState, useEffect, useRef } from 'react';
import { Columns2, Square, Zap } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { toast } from 'sonner';
import { bulkGenerate } from '@/lib/ideation/bulkGenerate';
import { seedCalendarHolidays, hasAutoGeneratedEvents } from '@/lib/ideation/seedCalendar';
import { supabase } from '@/integrations/supabase/client';

type LayoutMode = 'split' | 'single';

export default function IdeatePage() {
  const { brandId } = useParams<{ brandId: string }>();
  const navigate = useNavigate();
  const [layoutMode, setLayoutMode] = useState<LayoutMode>(() => {
    return (localStorage.getItem('ideation-layout') as LayoutMode) || 'split';
  });
  const [singleTab, setSingleTab] = useState<'ideation' | 'tasks'>('ideation');
  const [bulkConfirmOpen, setBulkConfirmOpen] = useState(false);
  const [bulkProgress, setBulkProgress] = useState<{ completed: number; total: number } | null>(null);
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeDragItem, setActiveDragItem] = useState<any>(null);
  const seededRef = useRef(false);

  const ideation = useIdeation(brandId!);
  const designQueue = useDesignQueue(brandId!);
  const calendar = useIdeationCalendar(brandId!);

  const hasStarted = ideation.nodes.length > 0;
  const selectedIdsSet = new Set(ideation.selectedIdeas.keys());

  useEffect(() => {
    if (!brandId || seededRef.current) return;
    seededRef.current = true;
    hasAutoGeneratedEvents(brandId).then(has => {
      if (!has) seedCalendarHolidays(brandId);
    });
  }, [brandId]);

  useEffect(() => {
    localStorage.setItem('ideation-layout', layoutMode);
  }, [layoutMode]);

  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 8 } }),
  );

  const handleAddToQueue = (idea: CampaignIdea, sendDate?: string) => {
    designQueue.addToQueue.mutate({
      idea,
      sessionId: ideation.sessionId,
      sendDate: sendDate || null,
    });
  };

  const handleBuildNow = async (idea: CampaignIdea) => {
    const { data: campaign, error } = await supabase
      .from('campaigns')
      .insert({
        brand_id: brandId!,
        name: idea.title,
        brief: idea.campaign_info || idea.description || null,
        goal: idea.campaign_type || 'promotional',
        extra_copy: idea.copy_direction || null,
        subject_line: idea.subject_line || null,
        status: 'draft',
      })
      .select('id')
      .single();

    if (error || !campaign) {
      toast.error(error?.message || 'Failed to create campaign');
      return;
    }
    navigate(`/brands/${brandId}/campaigns/${campaign.id}`);
  };

  const handleDragStart = (event: any) => {
    const data = event.active.data.current;
    if (data?.type === 'idea') setActiveDragItem(data.idea);
    else if (data?.type === 'queue-item') setActiveDragItem(data.item);
  };

  const handleDragEnd = (event: DragEndEvent) => {
    setActiveDragItem(null);
    const { active, over } = event;
    if (!over) return;

    const dragData = active.data.current as any;
    const dropId = over.id as string;

    if (dragData?.type === 'idea') {
      if (dropId === 'design-queue') {
        handleAddToQueue(dragData.idea);
      } else if (dropId.startsWith('calendar-day-')) {
        const date = dropId.replace('calendar-day-', '');
        handleAddToQueue(dragData.idea, date);
      }
    }

    if (dragData?.type === 'queue-item') {
      if (dropId === 'design-queue') {
        designQueue.clearDate.mutate(dragData.item.id);
      } else if (dropId.startsWith('calendar-day-')) {
        const date = dropId.replace('calendar-day-', '');
        designQueue.setDate.mutate({ id: dragData.item.id, date });
      }
    }
  };

  const eligibleForBulk = designQueue.items.filter(i => i.status === 'draft');

  const handleBulkGenerate = async () => {
    setBulkConfirmOpen(false);
    const items = [...eligibleForBulk];
    setBulkProgress({ completed: 0, total: items.length });

    const results = await bulkGenerate(
      items,
      brandId!,
      (completed, total) => setBulkProgress({ completed, total }),
      (itemId, status) => designQueue.updateStatus.mutate({ id: itemId, status }),
    );

    setBulkProgress(null);
    const succeeded = results.filter(r => r.success).length;
    const failed = results.filter(r => !r.success).length;
    if (failed > 0) {
      toast.error(`Bulk generation: ${succeeded}/${results.length} succeeded, ${failed} failed`);
    } else {
      toast.success(`Bulk generation complete — ${succeeded} campaigns generated`);
    }
  };

  const handleTypeFromMenu = (type: string, sub?: string) => {
    setMenuOpen(false);
    ideation.generateForType(type, sub);
  };

  const handleClearChat = async () => {
    // Clear the current session's nodes in the DB, then reset local state
    if (ideation.sessionId) {
      await supabase
        .from('ideation_sessions')
        .update({ nodes: [], status: 'completed' } as any)
        .eq('id', ideation.sessionId);
    }
    ideation.startNewSession();
  };

  const handleAddSelectedToQueue = () => {
    const selectedIdeas = Array.from(ideation.selectedIdeas.values());
    selectedIdeas.forEach(idea => {
      handleAddToQueue(idea);
    });
    ideation.clearSelection();
  };

  const ideationPanel = (
    <div className="flex flex-col h-full relative">
      {/* Scrollable content */}
      <div className="flex-1 overflow-y-auto overflow-x-hidden pb-36">
        {!hasStarted && (
          <div className="max-w-2xl mx-auto px-6">
            <div className="text-center mt-16 mb-8">
              <p className="text-sm text-muted-foreground">Pick a campaign type to get started</p>
            </div>
            <CampaignTypePicker
              onSelectType={(type, sub) => ideation.generateForType(type, sub)}
              activeType={ideation.activeType}
              isCompact={false}
            />
          </div>
        )}

        {hasStarted && (
          <>
            <NodeFlow
              nodes={ideation.nodes}
              streamingIdeas={ideation.streamingIdeas}
              streamingNodeId={ideation.streamingNodeId}
              selectedIds={selectedIdsSet}
              isTurbo={ideation.turboMode}
              isGenerating={ideation.isGenerating}
              onToggleSelect={ideation.toggleSelect}
              onAddToQueue={handleAddToQueue}
              onBuildNow={handleBuildNow}
              researchStatus={ideation.researchStatus}
            />
          </>
        )}
      </div>

      {/* Floating ChatBar */}
      <div className="absolute bottom-4 left-4 right-4 z-50">
        <ChatBar
          onSend={ideation.sendChat}
          isGenerating={ideation.isGenerating}
          isChatting={ideation.isChatting}
          selectedCount={ideation.selectedIdeas.size}
          onClearSelection={ideation.clearSelection}
          chaosMode={ideation.chaosMode}
          turboMode={ideation.turboMode}
          onToggleChaos={ideation.toggleChaosMode}
          onToggleTurbo={ideation.toggleTurboMode}
          activeType={ideation.activeType}
          onStop={() => ideation.abort()}
          menuOpen={menuOpen}
          onToggleMenu={() => setMenuOpen(!menuOpen)}
          onClearChat={handleClearChat}
          onAddToQueue={handleAddSelectedToQueue}
        />
      </div>

      {/* Menu overlay */}
      {menuOpen && (
        <div className="absolute bottom-28 left-4 right-4 z-[60]">
          <div className="bg-card border border-border rounded-xl shadow-lg p-4">
            <CampaignTypePicker
              onSelectType={handleTypeFromMenu}
              activeType={ideation.activeType}
              isCompact={false}
            />
          </div>
        </div>
      )}
    </div>
  );

  const taskPanel = (
    <TaskWindow
      items={designQueue.items}
      brandId={brandId!}
      calendarData={calendar.calendarData}
      onRequestMonths={calendar.handleRequestMonths}
      onRemove={(id) => designQueue.removeFromQueue.mutate(id)}
      onStatusChange={(id, status) => designQueue.updateStatus.mutate({ id, status })}
      bulkEligibleCount={eligibleForBulk.length}
      onBulkGenerate={() => setBulkConfirmOpen(true)}
      bulkProgress={bulkProgress}
    />
  );

  return (
    <DndContext sensors={sensors} onDragStart={handleDragStart} onDragEnd={handleDragEnd}>
      <div className="h-screen flex flex-col bg-background text-foreground">
        {/* Minimal top bar — layout toggle only */}
        <div className="h-9 flex items-center justify-end px-3 border-b border-border flex-shrink-0">
          <div className="flex items-center gap-0.5">
            <button
              onClick={() => setLayoutMode('split')}
              className={`p-1.5 rounded transition-colors ${layoutMode === 'split' ? 'bg-muted text-foreground' : 'text-muted-foreground hover:text-foreground'}`}
              title="Split view"
            >
              <Columns2 className="w-3.5 h-3.5" />
            </button>
            <button
              onClick={() => setLayoutMode('single')}
              className={`p-1.5 rounded transition-colors ${layoutMode === 'single' ? 'bg-muted text-foreground' : 'text-muted-foreground hover:text-foreground'}`}
              title="Single view"
            >
              <Square className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>

        {/* Main content */}
        <div className="flex-1 min-h-0">
          {layoutMode === 'split' ? (
            <ResizablePanelGroup direction="horizontal" className="h-full">
              <ResizablePanel defaultSize={50} minSize={30}>
                {ideationPanel}
              </ResizablePanel>
              <ResizableHandle withHandle />
              <ResizablePanel defaultSize={50} minSize={25}>
                {taskPanel}
              </ResizablePanel>
            </ResizablePanelGroup>
          ) : (
            <div className="h-full flex flex-col">
              {/* Single view tabs */}
              <div className="flex border-b border-border flex-shrink-0">
                <button
                  onClick={() => setSingleTab('ideation')}
                  className={`px-4 py-2 text-sm font-medium border-b-2 -mb-px transition-colors ${
                    singleTab === 'ideation'
                      ? 'border-foreground text-foreground'
                      : 'border-transparent text-muted-foreground hover:text-foreground'
                  }`}
                >
                  Ideation
                </button>
                <button
                  onClick={() => setSingleTab('tasks')}
                  className={`px-4 py-2 text-sm font-medium border-b-2 -mb-px transition-colors ${
                    singleTab === 'tasks'
                      ? 'border-foreground text-foreground'
                      : 'border-transparent text-muted-foreground hover:text-foreground'
                  }`}
                >
                  Tasks
                  {designQueue.items.length > 0 && (
                    <span className="ml-1.5 text-[10px] bg-muted px-1.5 py-0.5 rounded-full">
                      {designQueue.items.length}
                    </span>
                  )}
                </button>
              </div>
              <div className="flex-1 min-h-0">
                {singleTab === 'ideation' ? ideationPanel : taskPanel}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Drag overlay */}
      <DragOverlay>
        {activeDragItem && (
          <div className="bg-card border border-border rounded-lg shadow-lg px-3 py-2 max-w-[240px] opacity-90">
            <p className="text-xs font-medium text-foreground truncate">{activeDragItem.title}</p>
            {activeDragItem.campaign_type && (
              <p className="text-[10px] text-muted-foreground">{activeDragItem.campaign_type}</p>
            )}
          </div>
        )}
      </DragOverlay>

      {/* Bulk generate confirmation */}
      <Dialog open={bulkConfirmOpen} onOpenChange={setBulkConfirmOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Generate {eligibleForBulk.length} campaigns?</DialogTitle>
            <DialogDescription>
              This will create email drafts for all queued items. Campaigns will be generated 3 at a time.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setBulkConfirmOpen(false)}>Cancel</Button>
            <Button onClick={handleBulkGenerate}>
              <Zap className="w-4 h-4 mr-1" />
              Generate {eligibleForBulk.length}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </DndContext>
  );
}
