import { useParams, useNavigate } from 'react-router-dom';
import { DndContext, DragEndEvent, DragOverlay, useSensor, useSensors, PointerSensor } from '@dnd-kit/core';
import { useIdeation } from '@/hooks/useIdeation';
import { useDesignQueue } from '@/hooks/useDesignQueue';
import { useIdeationCalendar } from '@/hooks/useIdeationCalendar';
import { CampaignTypePicker } from '@/components/ideation/CampaignTypePicker';
import { NodeFlow } from '@/components/ideation/NodeFlow';
import { ChatBar } from '@/components/ideation/ChatBar';
import { TaskWindow } from '@/components/ideation/TaskWindow';
import { ResizablePanelGroup, ResizablePanel, ResizableHandle } from '@/components/ui/resizable';
import { CampaignIdea } from '@/lib/types';
import { useState, useEffect, useRef, useCallback, useLayoutEffect } from 'react';
import { Zap, List, CalendarDays, Star, ChevronLeft, ChevronRight } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { bulkGenerate } from '@/lib/ideation/bulkGenerate';
import { seedCalendarHolidays, hasAutoGeneratedEvents } from '@/lib/ideation/seedCalendar';
import { supabase } from '@/integrations/supabase/client';

type PageMode = 'ideate' | 'campaigns' | 'split';
type ViewMode = 'list' | 'calendar';

export default function IdeatePage() {
  const { brandId } = useParams<{ brandId: string }>();
  const navigate = useNavigate();
  const [pageMode, setPageMode] = useState<PageMode>(() => {
    return (localStorage.getItem('ideation-page-mode') as PageMode) || 'split';
  });
  const [bulkConfirmOpen, setBulkConfirmOpen] = useState(false);
  const [bulkProgress, setBulkProgress] = useState<{ completed: number; total: number } | null>(null);
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeDragItem, setActiveDragItem] = useState<any>(null);
  const seededRef = useRef(false);

  // Lifted TaskWindow state
  const [taskView, setTaskView] = useState<ViewMode>(() => {
    return (localStorage.getItem('ideation-default-view') as ViewMode) || 'list';
  });
  const [defaultTaskView, setDefaultTaskView] = useState<ViewMode>(() => {
    return (localStorage.getItem('ideation-default-view') as ViewMode) || 'list';
  });
  const [currentMonth, setCurrentMonth] = useState(() => {
    const now = new Date();
    return new Date(now.getFullYear(), now.getMonth(), 1);
  });

  const ideation = useIdeation(brandId!);
  const designQueue = useDesignQueue(brandId!);
  const calendar = useIdeationCalendar(brandId!);

  const hasStarted = ideation.nodes.length > 0;
  const selectedIdsSet = new Set(ideation.selectedIdeas.keys());

  const monthLabel = currentMonth.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });

  const goToPrev = useCallback(() => {
    const prev = new Date(currentMonth.getFullYear(), currentMonth.getMonth() - 1, 1);
    setCurrentMonth(prev);
    calendar.handleRequestMonths([prev]);
  }, [currentMonth, calendar.handleRequestMonths]);

  const goToNext = useCallback(() => {
    const next = new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1, 1);
    setCurrentMonth(next);
    calendar.handleRequestMonths([next]);
  }, [currentMonth, calendar.handleRequestMonths]);

  const goToToday = useCallback(() => {
    const now = new Date();
    const t = new Date(now.getFullYear(), now.getMonth(), 1);
    setCurrentMonth(t);
    calendar.handleRequestMonths([t]);
  }, [calendar.handleRequestMonths]);

  const handleStarView = (v: ViewMode) => {
    setDefaultTaskView(v);
    localStorage.setItem('ideation-default-view', v);
  };

  useEffect(() => {
    if (!brandId || seededRef.current) return;
    seededRef.current = true;
    hasAutoGeneratedEvents(brandId).then(has => {
      if (!has) seedCalendarHolidays(brandId);
    });
  }, [brandId]);

  useEffect(() => {
    localStorage.setItem('ideation-page-mode', pageMode);
  }, [pageMode]);

  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 8 } }),
  );

  const handleAddToQueue = (idea: CampaignIdea, sendDate?: string) => {
    designQueue.addToQueue.mutate({
      idea,
      sessionId: ideation.sessionId,
      sendDate: sendDate || null,
    });
  };

  const handleBuildNow = async (idea: CampaignIdea) => {
    const { data: campaign, error } = await supabase
      .from('campaigns')
      .insert({
        brand_id: brandId!,
        name: idea.title,
        brief: idea.campaign_info || idea.description || null,
        goal: idea.campaign_type || 'promotional',
        extra_copy: idea.copy_direction || null,
        subject_line: idea.subject_line || null,
        status: 'draft',
      })
      .select('id')
      .single();

    if (error || !campaign) {
      toast.error(error?.message || 'Failed to create campaign');
      return;
    }
    navigate(`/brands/${brandId}/campaigns/${campaign.id}`);
  };

  const handleDragStart = (event: any) => {
    const data = event.active.data.current;
    if (data?.type === 'idea') setActiveDragItem(data.idea);
    else if (data?.type === 'queue-item') setActiveDragItem(data.item);
  };

  const handleDragEnd = (event: DragEndEvent) => {
    setActiveDragItem(null);
    const { active, over } = event;
    if (!over) return;

    const dragData = active.data.current as any;
    const dropId = over.id as string;

    if (dragData?.type === 'idea') {
      if (dropId === 'design-queue') {
        handleAddToQueue(dragData.idea);
      } else if (dropId.startsWith('calendar-day-')) {
        const date = dropId.replace('calendar-day-', '');
        handleAddToQueue(dragData.idea, date);
      }
    }

    if (dragData?.type === 'queue-item') {
      if (dropId === 'design-queue') {
        designQueue.clearDate.mutate(dragData.item.id);
      } else if (dropId.startsWith('calendar-day-')) {
        const date = dropId.replace('calendar-day-', '');
        designQueue.setDate.mutate({ id: dragData.item.id, date });
      }
    }
  };

  const eligibleForBulk = designQueue.items.filter(i => i.status === 'draft');

  const handleBulkGenerate = async () => {
    setBulkConfirmOpen(false);
    const items = [...eligibleForBulk];
    setBulkProgress({ completed: 0, total: items.length });

    const results = await bulkGenerate(
      items,
      brandId!,
      (completed, total) => setBulkProgress({ completed, total }),
      (itemId, status) => designQueue.updateStatus.mutate({ id: itemId, status }),
    );

    setBulkProgress(null);
    const succeeded = results.filter(r => r.success).length;
    const failed = results.filter(r => !r.success).length;
    if (failed > 0) {
      toast.error(`Bulk generation: ${succeeded}/${results.length} succeeded, ${failed} failed`);
    } else {
      toast.success(`Bulk generation complete — ${succeeded} campaigns generated`);
    }
  };

  const handleTypeFromMenu = (type: string, sub?: string) => {
    setMenuOpen(false);
    ideation.generateForType(type, sub);
  };

  const handleClearChat = async () => {
    if (ideation.sessionId) {
      await supabase
        .from('ideation_sessions')
        .update({ nodes: [], status: 'completed' } as any)
        .eq('id', ideation.sessionId);
    }
    ideation.startNewSession();
  };

  const handleAddSelectedToQueue = () => {
    const selectedIdeas = Array.from(ideation.selectedIdeas.values());
    selectedIdeas.forEach(idea => {
      handleAddToQueue(idea);
    });
    ideation.clearSelection();
  };

  // Show task controls when tasks panel is visible
  const showTaskControls = pageMode === 'split' || pageMode === 'campaigns';

  const PAGE_MODES: PageMode[] = ['ideate', 'campaigns', 'split'];
  const PAGE_MODE_LABELS: Record<PageMode, string> = { ideate: 'Ideate', campaigns: 'Campaigns', split: 'Split' };
  const activeModeIndex = PAGE_MODES.indexOf(pageMode);

  const ideationPanel = (
    <div className="flex flex-col h-full relative">
      <div className="flex-1 overflow-y-auto overflow-x-hidden pb-36">
        <div className="max-w-3xl mx-auto">
          {!hasStarted && (
            <div className="px-6">
              <div className="text-center mt-16 mb-8">
                <p className="text-sm text-muted-foreground">Pick a campaign type to get started</p>
              </div>
              <CampaignTypePicker
                onSelectType={(type, sub) => ideation.generateForType(type, sub)}
                activeType={ideation.activeType}
                isCompact={false}
              />
            </div>
          )}

          {hasStarted && (
            <NodeFlow
              nodes={ideation.nodes}
              streamingIdeas={ideation.streamingIdeas}
              streamingNodeId={ideation.streamingNodeId}
              selectedIds={selectedIdsSet}
              isTurbo={ideation.turboMode}
              isGenerating={ideation.isGenerating}
              onToggleSelect={ideation.toggleSelect}
              onAddToQueue={handleAddToQueue}
              onBuildNow={handleBuildNow}
              researchStatus={ideation.researchStatus}
            />
          )}
        </div>
      </div>

      <div className="absolute bottom-4 left-0 right-0 z-50 flex justify-center px-4">
        <div className="w-full max-w-3xl">
          <ChatBar
            onSend={ideation.sendChat}
            isGenerating={ideation.isGenerating}
            isChatting={ideation.isChatting}
            selectedCount={ideation.selectedIdeas.size}
            onClearSelection={ideation.clearSelection}
            chaosMode={ideation.chaosMode}
            turboMode={ideation.turboMode}
            onToggleChaos={ideation.toggleChaosMode}
            onToggleTurbo={ideation.toggleTurboMode}
            activeType={ideation.activeType}
            onStop={() => ideation.abort()}
            menuOpen={menuOpen}
            onToggleMenu={() => setMenuOpen(!menuOpen)}
            onClearChat={handleClearChat}
            onAddToQueue={handleAddSelectedToQueue}
          />
        </div>
      </div>

      {menuOpen && (
        <div className="absolute bottom-28 left-0 right-0 z-[60] flex justify-center px-4">
          <div className="w-full max-w-3xl bg-card border border-border rounded-xl shadow-lg p-4">
            <CampaignTypePicker
              onSelectType={handleTypeFromMenu}
              activeType={ideation.activeType}
              isCompact={false}
            />
          </div>
        </div>
      )}
    </div>
  );

  const taskPanel = (
    <TaskWindow
      items={designQueue.items}
      brandId={brandId!}
      calendarData={calendar.calendarData}
      onRequestMonths={calendar.handleRequestMonths}
      onRemove={(id) => designQueue.removeFromQueue.mutate(id)}
      onStatusChange={(id, status) => designQueue.updateStatus.mutate({ id, status })}
      onAddTask={(sendDate) => {
        handleAddToQueue({ id: crypto.randomUUID(), title: 'Untitled Task', campaign_type: '', description: '', subject_line: '', campaign_info: '', copy_direction: '' }, sendDate);
      }}
      bulkEligibleCount={eligibleForBulk.length}
      onBulkGenerate={() => setBulkConfirmOpen(true)}
      bulkProgress={bulkProgress}
      view={taskView}
      currentMonth={currentMonth}
    />
  );

  return (
    <DndContext sensors={sensors} onDragStart={handleDragStart} onDragEnd={handleDragEnd}>
      <div className="h-screen flex flex-col bg-background text-foreground">
        {/* Single unified top bar */}
        <div className="h-10 flex items-center justify-between px-3 border-b border-border flex-shrink-0">
          {/* Left: spacer for balance */}
          <div className="flex-1" />

          {/* Center: 3-way page mode selector */}
          <div className="relative flex items-center bg-muted/60 rounded-full p-0.5">
            {/* Sliding pill indicator */}
            <div
              className="absolute top-0.5 bottom-0.5 rounded-full bg-foreground shadow-sm transition-all duration-300 ease-[cubic-bezier(0.4,0,0.2,1)]"
              style={{
                width: `calc(${100 / PAGE_MODES.length}% - 2px)`,
                left: `calc(${activeModeIndex} * ${100 / PAGE_MODES.length}% + 1px)`,
              }}
            />
            {PAGE_MODES.map((mode) => (
              <button
                key={mode}
                onClick={() => setPageMode(mode)}
                className={`relative z-10 px-5 py-1 text-xs font-medium rounded-full transition-colors duration-300 ${
                  pageMode === mode
                    ? 'text-background'
                    : 'text-muted-foreground hover:text-foreground'
                }`}
              >
                {PAGE_MODE_LABELS[mode]}
              </button>
            ))}
          </div>

          {/* Right: task view controls */}
          <div className="flex items-center gap-1 min-w-0 flex-1 justify-end">
            {showTaskControls && (
              <>
                <button
                  onClick={() => setTaskView('list')}
                  className={`p-1.5 rounded transition-colors ${
                    taskView === 'list' ? 'bg-muted text-foreground' : 'text-muted-foreground hover:text-foreground hover:bg-muted/50'
                  }`}
                  title="List view"
                >
                  <List className="w-3.5 h-3.5" />
                </button>
                <button
                  onClick={() => handleStarView(taskView)}
                  className={`p-0.5 rounded transition-colors ${
                    defaultTaskView === taskView ? 'text-amber-500' : 'text-muted-foreground/30 hover:text-muted-foreground'
                  }`}
                  title={defaultTaskView === taskView ? 'Default view' : 'Set as default'}
                >
                  <Star className={`w-3 h-3 ${defaultTaskView === taskView ? 'fill-current' : ''}`} />
                </button>
                <button
                  onClick={() => setTaskView('calendar')}
                  className={`p-1.5 rounded transition-colors ${
                    taskView === 'calendar' ? 'bg-muted text-foreground' : 'text-muted-foreground hover:text-foreground hover:bg-muted/50'
                  }`}
                  title="Calendar view"
                >
                  <CalendarDays className="w-3.5 h-3.5" />
                </button>

                {taskView === 'calendar' && (
                  <div className="flex items-center gap-0.5 ml-1">
                    <button onClick={goToPrev} className="p-1 rounded hover:bg-muted text-muted-foreground hover:text-foreground transition-colors">
                      <ChevronLeft className="w-3.5 h-3.5" />
                    </button>
                    <span className="text-[10px] font-semibold text-foreground min-w-[90px] text-center">{monthLabel}</span>
                    <button onClick={goToNext} className="p-1 rounded hover:bg-muted text-muted-foreground hover:text-foreground transition-colors">
                      <ChevronRight className="w-3.5 h-3.5" />
                    </button>
                    <button onClick={goToToday} className="text-[10px] text-muted-foreground hover:text-foreground transition-colors px-1.5 py-0.5 rounded hover:bg-muted">
                      Today
                    </button>
                  </div>
                )}
              </>
            )}
          </div>
        </div>

        {/* Main content */}
        <div className="flex-1 min-h-0">
          {pageMode === 'split' ? (
            <ResizablePanelGroup direction="horizontal" className="h-full">
              <ResizablePanel defaultSize={50} minSize={30}>
                {ideationPanel}
              </ResizablePanel>
              <ResizableHandle withHandle />
              <ResizablePanel defaultSize={50} minSize={25}>
                {taskPanel}
              </ResizablePanel>
            </ResizablePanelGroup>
          ) : pageMode === 'ideate' ? (
            <div className="h-full">{ideationPanel}</div>
          ) : (
            <div className="h-full">{taskPanel}</div>
          )}
        </div>
      </div>

      {/* Drag overlay */}
      <DragOverlay>
        {activeDragItem && (
          <div className="bg-card border border-border rounded-lg shadow-lg px-3 py-2 max-w-[240px] opacity-90">
            <p className="text-xs font-medium text-foreground truncate">{activeDragItem.title}</p>
            {activeDragItem.campaign_type && (
              <p className="text-[10px] text-muted-foreground">{activeDragItem.campaign_type}</p>
            )}
          </div>
        )}
      </DragOverlay>

      {/* Bulk generate confirmation */}
      <Dialog open={bulkConfirmOpen} onOpenChange={setBulkConfirmOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Generate {eligibleForBulk.length} campaigns?</DialogTitle>
            <DialogDescription>
              This will create email drafts for all queued items. Campaigns will be generated 3 at a time.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setBulkConfirmOpen(false)}>Cancel</Button>
            <Button onClick={handleBulkGenerate}>
              <Zap className="w-4 h-4 mr-1" />
              Generate {eligibleForBulk.length}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </DndContext>
  );
}
