import { useParams, useNavigate } from 'react-router-dom';
import { DndContext, DragEndEvent, useSensor, useSensors, PointerSensor } from '@dnd-kit/core';
import { useIdeation } from '@/hooks/useIdeation';
import { useDesignQueue } from '@/hooks/useDesignQueue';
import { useIdeationCalendar } from '@/hooks/useIdeationCalendar';
import { CampaignTypePicker } from '@/components/ideation/CampaignTypePicker';
import { NodeFlow } from '@/components/ideation/NodeFlow';
import { ChatBar } from '@/components/ideation/ChatBar';
import { DesignQueue } from '@/components/ideation/DesignQueue';
import { IdeationCalendar } from '@/components/ideation/IdeationCalendar';
import { GenerationDrawer } from '@/components/ideation/GenerationDrawer';
import { CampaignIdea } from '@/lib/types';
import { DesignQueueItem } from '@/hooks/useDesignQueue';
import { useState, useEffect, useRef } from 'react';
import { ArrowLeft, Zap, PanelRightOpen, PanelRightClose } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { toast } from 'sonner';
import { bulkGenerate } from '@/lib/ideation/bulkGenerate';
import { seedCalendarHolidays, hasAutoGeneratedEvents } from '@/lib/ideation/seedCalendar';
import { supabase } from '@/integrations/supabase/client';

export default function IdeatePage() {
  const { brandId } = useParams<{ brandId: string }>();
  const navigate = useNavigate();
  const [rightPanelOpen, setRightPanelOpen] = useState(true);
  const [mobileTab, setMobileTab] = useState<'queue' | 'calendar' | null>(null);
  const [drawerItem, setDrawerItem] = useState<DesignQueueItem | null>(null);
  const [bulkConfirmOpen, setBulkConfirmOpen] = useState(false);
  const [bulkProgress, setBulkProgress] = useState<{ completed: number; total: number } | null>(null);
  const [menuOpen, setMenuOpen] = useState(false);
  const seededRef = useRef(false);

  const ideation = useIdeation(brandId!);
  const designQueue = useDesignQueue(brandId!);
  const calendar = useIdeationCalendar(brandId!);

  const hasStarted = ideation.nodes.length > 0;
  const selectedIdsSet = new Set(ideation.selectedIdeas.keys());

  // Auto-seed holidays on first visit
  useEffect(() => {
    if (!brandId || seededRef.current) return;
    seededRef.current = true;
    hasAutoGeneratedEvents(brandId).then(has => {
      if (!has) seedCalendarHolidays(brandId);
    });
  }, [brandId]);

  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 8 } }),
  );

  const handleAddToQueue = (idea: CampaignIdea, sendDate?: string) => {
    designQueue.addToQueue.mutate({
      idea,
      sessionId: ideation.sessionId,
      sendDate: sendDate || null,
    });
  };

  const handleBuildNow = async (idea: CampaignIdea) => {
    const { data: campaign, error } = await supabase
      .from('campaigns')
      .insert({
        brand_id: brandId!,
        name: idea.title,
        brief: idea.campaign_info || idea.description || null,
        goal: idea.campaign_type || 'promotional',
        extra_copy: idea.copy_direction || null,
        subject_line: idea.subject_line || null,
        status: 'draft',
      })
      .select('id')
      .single();

    if (error || !campaign) {
      toast.error(error?.message || 'Failed to create campaign');
      return;
    }
    navigate(`/brands/${brandId}/campaigns/${campaign.id}`);
  };

  const handleDragEnd = (event: DragEndEvent) => {
    const { active, over } = event;
    if (!over) return;

    const dragData = active.data.current as any;
    const dropId = over.id as string;

    if (dragData?.type === 'idea') {
      if (dropId === 'design-queue') {
        handleAddToQueue(dragData.idea);
      } else if (dropId.startsWith('calendar-day-')) {
        const date = dropId.replace('calendar-day-', '');
        handleAddToQueue(dragData.idea, date);
      }
    }

    if (dragData?.type === 'queue-item') {
      if (dropId === 'design-queue') {
        designQueue.clearDate.mutate(dragData.item.id);
      } else if (dropId.startsWith('calendar-day-')) {
        const date = dropId.replace('calendar-day-', '');
        designQueue.setDate.mutate({ id: dragData.item.id, date });
      }
    }
  };

  const eligibleForBulk = designQueue.items.filter(i => i.status === 'queued' || i.status === 'configured');

  const handleBulkGenerate = async () => {
    setBulkConfirmOpen(false);
    const items = [...eligibleForBulk];
    setBulkProgress({ completed: 0, total: items.length });

    const results = await bulkGenerate(
      items,
      brandId!,
      (completed, total) => setBulkProgress({ completed, total }),
      (itemId, status) => designQueue.updateStatus.mutate({ id: itemId, status }),
    );

    setBulkProgress(null);
    const succeeded = results.filter(r => r.success).length;
    const failed = results.filter(r => !r.success).length;
    if (failed > 0) {
      toast.error(`Bulk generation: ${succeeded}/${results.length} succeeded, ${failed} failed`);
    } else {
      toast.success(`Bulk generation complete — ${succeeded} campaigns generated`);
    }
  };

  const handleTypeFromMenu = (type: string, sub?: string) => {
    setMenuOpen(false);
    ideation.generateForType(type, sub);
  };

  return (
    <DndContext sensors={sensors} onDragEnd={handleDragEnd}>
      <div className="h-screen flex flex-col bg-[#0f1117] text-white ideation-glow">
        {/* Header */}
        <div className="h-12 flex items-center justify-between px-4 flex-shrink-0 relative z-10">
          <div className="flex items-center gap-3">
            <button
              onClick={() => navigate(`/brands/${brandId}`)}
              className="w-7 h-7 rounded-lg flex items-center justify-center text-white/40 hover:text-white/80 transition-colors"
            >
              <ArrowLeft className="w-4 h-4" />
            </button>
            <div className="w-5 h-5 rounded bg-white/10 flex items-center justify-center">
              <span className="text-[9px] font-bold text-white/60">ID</span>
            </div>
            <span className="text-[12px] tracking-wide text-white/50 uppercase font-medium">ID8</span>
          </div>
          <button
            onClick={() => setRightPanelOpen(!rightPanelOpen)}
            className="p-1.5 rounded-lg text-white/40 hover:text-white/80 transition-colors hidden lg:flex"
          >
            {rightPanelOpen ? <PanelRightClose className="w-4 h-4" /> : <PanelRightOpen className="w-4 h-4" />}
          </button>
        </div>

        {/* Main content */}
        <div className="flex-1 flex overflow-hidden relative z-10">
          {/* Left Panel — Ideation Flow */}
          <div className={`flex flex-col ${rightPanelOpen ? 'w-full lg:w-[60%]' : 'w-full'} transition-all relative`}>
            {/* Scrollable content area */}
            <div className="flex-1 overflow-y-auto pb-36">
              {!hasStarted && (
                <div className="max-w-3xl mx-auto px-6">
                  <div className="text-center mt-16 mb-8">
                    <p className="text-sm text-white/50">Pick a campaign type to get started</p>
                  </div>
                  <CampaignTypePicker
                    onSelectType={(type, sub) => ideation.generateForType(type, sub)}
                    activeType={ideation.activeType}
                    isCompact={false}
                  />
                </div>
              )}

              {hasStarted && (
                <>
                  {/* Compact type picker */}
                  <CampaignTypePicker
                    onSelectType={(type, sub) => ideation.generateForType(type, sub)}
                    activeType={ideation.activeType}
                    isCompact={true}
                  />
                  <NodeFlow
                    nodes={ideation.nodes}
                    streamingIdeas={ideation.streamingIdeas}
                    streamingNodeId={ideation.streamingNodeId}
                    selectedIds={selectedIdsSet}
                    isTurbo={ideation.turboMode}
                    onToggleSelect={ideation.toggleSelect}
                    onAddToQueue={handleAddToQueue}
                    onBuildNow={handleBuildNow}
                    researchStatus={ideation.researchStatus}
                  />
                </>
              )}
            </div>

            {/* Floating ChatBar */}
            <ChatBar
              onSend={ideation.sendChat}
              isGenerating={ideation.isGenerating}
              isChatting={ideation.isChatting}
              selectedCount={ideation.selectedIdeas.size}
              onClearSelection={ideation.clearSelection}
              chaosMode={ideation.chaosMode}
              turboMode={ideation.turboMode}
              onToggleChaos={ideation.toggleChaosMode}
              onToggleTurbo={ideation.toggleTurboMode}
              activeType={ideation.activeType}
              onStop={() => ideation.abort()}
              menuOpen={menuOpen}
              onToggleMenu={() => setMenuOpen(!menuOpen)}
            />

            {/* Menu overlay — type picker popup above ChatBar */}
            {menuOpen && (
              <div className="fixed bottom-32 left-1/2 -translate-x-1/2 z-[60] w-full max-w-[700px] px-4">
                <div className="glass-input p-4">
                  <CampaignTypePicker
                    onSelectType={handleTypeFromMenu}
                    activeType={ideation.activeType}
                    isCompact={false}
                  />
                </div>
              </div>
            )}
          </div>

          {/* Right Panel — Desktop */}
          {rightPanelOpen && (
            <div className="hidden lg:flex lg:w-[40%] flex-col border-l border-white/[0.06]">
              <div className="max-h-[35%] min-h-[120px] border-b border-white/[0.06] flex-shrink-0">
                <DesignQueue
                  items={designQueue.items}
                  onRemove={(id) => designQueue.removeFromQueue.mutate(id)}
                  onItemClick={(item) => setDrawerItem(item)}
                  bulkEligibleCount={eligibleForBulk.length}
                  onBulkGenerate={() => setBulkConfirmOpen(true)}
                  bulkProgress={bulkProgress}
                />
              </div>
              <div className="flex-1 min-h-0">
                <IdeationCalendar
                  calendarData={calendar.calendarData}
                  onRequestMonths={calendar.handleRequestMonths}
                  onPillClick={(item) => setDrawerItem(item)}
                />
              </div>
            </div>
          )}
        </div>

        {/* Mobile bottom tabs */}
        <div className="lg:hidden flex border-t border-white/[0.06] bg-[#0f1117]">
          <button
            onClick={() => setMobileTab(mobileTab === 'queue' ? null : 'queue')}
            className={`flex-1 py-2.5 text-xs font-medium text-center transition-colors ${
              mobileTab === 'queue' ? 'text-white bg-white/[0.06]' : 'text-white/50'
            }`}
          >
            Queue ({designQueue.items.length})
          </button>
          <button
            onClick={() => setMobileTab(mobileTab === 'calendar' ? null : 'calendar')}
            className={`flex-1 py-2.5 text-xs font-medium text-center transition-colors ${
              mobileTab === 'calendar' ? 'text-white bg-white/[0.06]' : 'text-white/50'
            }`}
          >
            Calendar
          </button>
        </div>

        {mobileTab && (
          <div className="lg:hidden fixed inset-x-0 bottom-10 h-[50vh] bg-[#0f1117] border-t border-white/[0.06] z-50 animate-in slide-in-from-bottom duration-200">
            {mobileTab === 'queue' ? (
              <DesignQueue
                items={designQueue.items}
                onRemove={(id) => designQueue.removeFromQueue.mutate(id)}
                onItemClick={(item) => setDrawerItem(item)}
                bulkEligibleCount={eligibleForBulk.length}
                onBulkGenerate={() => setBulkConfirmOpen(true)}
                bulkProgress={bulkProgress}
              />
            ) : (
              <IdeationCalendar
                calendarData={calendar.calendarData}
                onRequestMonths={calendar.handleRequestMonths}
                onPillClick={(item) => setDrawerItem(item)}
              />
            )}
          </div>
        )}
      </div>

      {drawerItem && (
        <GenerationDrawer
          item={drawerItem}
          brandId={brandId!}
          onClose={() => setDrawerItem(null)}
          onUpdate={(id, fields) => {}}
          onRemove={(id) => {
            designQueue.removeFromQueue.mutate(id);
            setDrawerItem(null);
          }}
          onStatusChange={(id, status) => {
            designQueue.updateStatus.mutate({ id, status });
          }}
        />
      )}

      <Dialog open={bulkConfirmOpen} onOpenChange={setBulkConfirmOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Generate {eligibleForBulk.length} campaigns?</DialogTitle>
            <DialogDescription>
              This will create email drafts for all queued items. Campaigns will be generated 3 at a time.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setBulkConfirmOpen(false)}>Cancel</Button>
            <Button onClick={handleBulkGenerate}>
              <Zap className="w-4 h-4 mr-1" />
              Generate {eligibleForBulk.length}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </DndContext>
  );
}
